### ISSUE TITLE
convert a (pytorch/onnx)model to NMSIS-NN

### ISSUE THREAD

**Issue by AngLi666** [Nuclei-Software/NMSIS#2]
1. Is there a toolchain can convert a (pytorch/onnx)model to NMSIS-NN?
2. If not [1], do you have any plan to develop this toolchain?
3. If you are not going to develop a convert toolchain, do you have any suggestions for users how to deploy pytorch/onnx model to NMSIS-NN(Nuclei 32BIT RISC-V MCU)

**Comment by fanghuaqi** [comment]
Not yet any plan to convert pytorch/onnx model to NMSIS-NN, if you want to take a try, you can try the following things:

1. tflite-micro: https://github.com/Nuclei-Software/tflite-micro/tree/nuclei_main/tensorflow/lite/micro/nuclei_demosoc
2. tengine(need some port using nmsis-nn): https://github.com/OAID/Tengine
3. any other opensource ai model deploy model tool, and you can adapt the tool to support NMSIS-NN api, if the tool already support CMSIS-NN, it will be easy to achieve it.

**Comment by AngLi666** [comment]
> Not yet any plan to convert pytorch/onnx model to NMSIS-NN, if you want to take a try, you can try the following things:
> 
> 1. tflite-micro: https://github.com/Nuclei-Software/tflite-micro/tree/nuclei_main/tensorflow/lite/micro/nuclei_demosoc
> 2. tengine(need some port using nmsis-nn): https://github.com/OAID/Tengine
> 3. any other opensource ai model deploy model tool, and you can adapt the tool to support NMSIS-NN api, if the tool already support CMSIS-NN, it will be easy to achieve it.

Thanks very much for your help! And I did some investigation regarding to your advice. 
1. It seems tflite-micro is the most suitable tool I could just right now. 
2. I am aware tengine could deploy model to general RISCV device. However, I am wondering how is its efficiency, comparing to NMSIS-NN?
3. This is the most proper way if I need to convert pytorch/onnx models. But developing new toolchain is exhausting. We may not be able to do it immediately.

Here are my new questions, I hope you can give me some feedback, Thanks very much!!!
1. Is there any misunderstanding about my above findings?
2. regarding to [1], did tflite-micro use NMSIS-NN library? if not, how is its efficiency, , comparing to NMSIS-NN?
3. regarding to [2], did tengine use NMSIS-NN library? if not, how is its efficiency, , comparing to NMSIS-NN?

**Comment by fanghuaqi** [comment]
> 

Currently tflite-micro support is using NMSIS-NN, you can take a try. For tengine, it may no use any of NMSIS-NN code, but you can port to it, if it has cmsis-nn support, it can be easily ported.

Thanks

**Comment by AngLi666** [comment]
> > 
> 
> Currently tflite-micro support is using NMSIS-NN, you can take a try. For tengine, it may no use any of NMSIS-NN code, but you can port to it, if it has cmsis-nn support, it can be easily ported.
> 
> Thanks

1. What do you meaning by porting NMSIS-NN to tengine? Do you mean adding new CODEGEN to Tengine for NMSIS-NN?  Could you explain it in detail? 
4. I did see some comments about converting cmsis-nn to nmsis-nn somewhere else, but I did not understand what meaning is that. Here is my naive guess: nmsis-nn a variant of cmsis-nn, which is made for RISCV. NMSIS-NN is roughly simultaneously developed. Generally speaking, their header files are synchronized (similar API). That is saying any CMSIS-NN api call can be replaced  by a corresponding NMSIS-NN api. I have no idea about the correnctness of my guess. Can you please give me more information about NMSIS-NN & CMSIS-NN and the "port" things in a Toolchain

**Comment by fanghuaqi** [comment]
1. yes
2. NMSIS-NN are designed to be api compatiable with CMSIS-NN, just replace `arm` to `riscv`, see https://doc.nucleisys.com/nmsis/nn/index.html

**Comment by AngLi666** [comment]
> 1. yes
> 2. NMSIS-NN are designed to be api compatiable with CMSIS-NN, just replace `arm` to `riscv`, see https://doc.nucleisys.com/nmsis/nn/index.html

1. Is there an existing opensource NMSIS-NN codegen I could use to migrate? Or I should implement it on my own?
